ENG-4504 Trying two separate while

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -103,27 +103,27 @@ jobs:
     - name: Verify EntandoApp installation
       run: |
         echo "Waiting for EntandoApp to be available. Estimated time: 5 minutes"
-        while true; do
+        while [ -z $deployment_name ]; do
           deployment_name=($(oc get deployment --selector entando.org/entando-resource-kind=EntandoPlugin -o jsonpath='{.items[0].metadata.name}' --ignore-not-found))
           if [ -n "$deployment_name" ]; then
-            echo "EntandoApp deployment started"
-            while true; do
-              deployment_status="$(oc rollout status deployment/$(echo $deployment_name))"
-              if [[ "$deployment_status" == *"successfully rolled out"* ]]; then
-                echo "EntandoApp is ready"
-                break 2
-              elif [[ "$deployment_status" == *"failed"* ]]; then
-                echo "EntandoApp deployment failed"
-                exit 1
-              else
-                echo "EntandoApp deployment not ready yet, waiting 5 seconds"
-              fi
-              sleep 5  
-            done
           else
             echo "EntandoApp deployment not created yet, waiting 15 seconds"
             sleep 15
           fi
+        done
+        echo "EntandoApp deployment started"
+        while true; do
+          deployment_status="$(oc rollout status deployment/$(echo $deployment_name))"
+          if [[ "$deployment_status" == *"successfully rolled out"* ]]; then
+            echo "EntandoApp is ready"
+            break
+          elif [[ "$deployment_status" == *"failed"* ]]; then
+            echo "EntandoApp deployment failed"
+            exit 1
+          else
+            echo "EntandoApp deployment not ready yet, waiting 5 seconds"
+          fi
+          sleep 5  
         done
   delete-namespace:
     name: Delete namespace
