ENG-4504 Waiting until EntandoApp is installed

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -99,7 +99,30 @@ jobs:
         entando_app_manifest=$"${entando_app_manifest//"{{appused}}"/"${{ env.ENTANDO_APP_USED }}"}"
         echo "${entando_app_manifest//"{{openshift_url}}"/"okd4-10.awsentando.net"}" > entando-app-manifest.yaml
         oc apply -f entando-app-manifest.yaml
-  
+    - name: Verify EntandoApp installation
+      run: |
+        while true; do
+          deployment_name=($(oc get deployment --selector entando.org/entando-resource-kind=EntandoPlugin -o jsonpath='{.items[0].metadata.name} --ignore-not-found'))
+          if [ -n "$deployment_available"]; then
+            echo "Deployment is available"
+            while true; do
+              deployment_status=($(oc rollout status deployment/$deployment_name))
+              if [[ $STATUS == *"successfully rolled out"* ]]; then
+                echo "Deployment succeeded!"
+                break
+              elif [[ $STATUS == *"failed"* ]]; then
+                echo "Deployment failed!"
+                exit 1
+              else
+                echo "Waiting for deployment to complete..."
+              fi
+              sleep 5  
+            done
+          else
+            echo "Deployment not yet available, waiting 5 seconds before retrying"
+            sleep 5
+          fi
+        done
   delete-namespace:
     name: Delete namespace
     runs-on: ubuntu-latest
