ENG-4504 Waiting for operator to be installed

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -81,6 +81,22 @@ jobs:
         subscription_manifest=$"${subscription_manifest//"{{namespace}}"/"${{ env.NAMESPACE }}"}"
         echo "${subscription_manifest//"{{source}}"/"${{ env.ENTANDO_OPERATOR_SOURCE }}"}" > subscription-manifest.yaml
         oc apply -f subscription-manifest.yaml
+    - name: Wait for Operator to be installed
+      run: |
+        echo "entando-k8s-operator is being installed. Estimated wait time: 15 seconds."
+        while true; do
+          installation_status=($(oc get clusterserviceversion entando-k8s-operator.v7.1.3 -o jsonpath='{.status.phase}' --ignore-not-found))
+          if [[ "$installation_status" == "Succeeded" ]]; then
+            echo "entando-k8s-operator is installed."
+            break
+          elif [[ "$installation_status" == "Failed" ]]; then
+            echo "entando-k8s-operator installation failed. Exiting."
+            exit 1
+          else
+            echo "entando-k8s-operator is currently not ready. Waiting for 5 seconds."
+            sleep 15
+          fi
+        done
     - name: Update app-engine image
       run: |
         oc get clusterserviceversion entando-k8s-operator.v7.1.3 -o yaml > operator.yaml
