ENG-4504 Moving step up

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -54,6 +54,31 @@ jobs:
     runs-on: ubuntu-latest
     needs: prepare-namespace
     steps:
+    - name: Verify EntandoApp installation
+      run: |
+        echo "Waiting for EntandoApp to be available. Estimated time: 5 minutes"
+        while true; do
+          deployment_name=($(oc get deployment --selector entando.org/entando-resource-kind=EntandoPlugin -o jsonpath='{.items[0].metadata.name}' --ignore-not-found))
+          if [ ! -z "$deployment_name"]; then
+            echo "EntandoApp deployment started"
+            while true; do
+              deployment_status=($(oc rollout status deployment/$(echo $deployment_name)))
+              if [ $deployment_status == *"successfully rolled out"* ]; then
+                echo "EntandoApp is ready"
+                break
+              elif [ $deployment_status == *"failed"* ]; then
+                echo "Deployment failed"
+                exit 1
+              else
+                echo "Waiting for deployment to complete..."
+              fi
+              sleep 5  
+            done
+          else
+            echo "EntandoApp not yet available, waiting 15 seconds before retrying"
+            sleep 15
+          fi
+        done
 #    - name: Login to OpenShift with JobConfiguration
 #      uses: redhat-actions/oc-login@v1
 #      with:
@@ -99,31 +124,31 @@ jobs:
 #        entando_app_manifest=$"${entando_app_manifest//"{{appused}}"/"${{ env.ENTANDO_APP_USED }}"}"
 #        echo "${entando_app_manifest//"{{openshift_url}}"/"${{ env.OPENSHIFT_DOMAIN }}"}" > entando-app-manifest.yaml
 #        oc apply -f entando-app-manifest.yaml
-    - name: Verify EntandoApp installation
-      run: |
-        echo "Waiting for EntandoApp to be available. Estimated time: 5 minutes"
-        while true; do
-          deployment_name=($(oc get deployment --selector entando.org/entando-resource-kind=EntandoPlugin -o jsonpath='{.items[0].metadata.name}' --ignore-not-found))
-          if [ ! -z "$deployment_name"]; then
-            echo "EntandoApp deployment started"
-            while true; do
-              deployment_status=($(oc rollout status deployment/$(echo $deployment_name)))
-              if [ $deployment_status == *"successfully rolled out"* ]; then
-                echo "EntandoApp is ready"
-                break
-              elif [ $deployment_status == *"failed"* ]; then
-                echo "Deployment failed"
-                exit 1
-              else
-                echo "Waiting for deployment to complete..."
-              fi
-              sleep 5  
-            done
-          else
-            echo "EntandoApp not yet available, waiting 15 seconds before retrying"
-            sleep 15
-          fi
-        done
+#    - name: Verify EntandoApp installation
+#      run: |
+#        echo "Waiting for EntandoApp to be available. Estimated time: 5 minutes"
+#        while true; do
+#          deployment_name=($(oc get deployment --selector entando.org/entando-resource-kind=EntandoPlugin -o jsonpath='{.items[0].metadata.name}' --ignore-not-found))
+#          if [ ! -z "$deployment_name"]; then
+#            echo "EntandoApp deployment started"
+#            while true; do
+#              deployment_status=($(oc rollout status deployment/$(echo $deployment_name)))
+#              if [ $deployment_status == *"successfully rolled out"* ]; then
+#                echo "EntandoApp is ready"
+#                break
+#              elif [ $deployment_status == *"failed"* ]; then
+#                echo "Deployment failed"
+#                exit 1
+#              else
+#                echo "Waiting for deployment to complete..."
+#              fi
+#              sleep 5  
+#            done
+#          else
+#            echo "EntandoApp not yet available, waiting 15 seconds before retrying"
+#            sleep 15
+#          fi
+#        done
   delete-namespace:
     name: Delete namespace
     runs-on: ubuntu-latest
